### PR TITLE
feat: add unique prefix to resource names

### PR DESCRIPTION
**Pull request by davidcavazos**
Fixes: #84 

Internal: [cl/629129167](http://cl/629129167)

Prefixing all resources with `knowledge-base-`.

This should avoid name clashes with other solutions.

### CODE REVIEW

**Review by NimJay — CHANGES_REQUESTED** [review]
Thanks for doing this, David! :)

Looks like `knowledge-base-trigger-sa-9c43dc` is too long (based on Terraform failures in GitHub checks).

What if we used `kb-` as a prefix or something else that's shorter?
I believe we need to stay at or below 30 characters.

**Comment by NimJay** [comment]
Also, feel free to ignore the `terraform-genai-knowledge-base-int-trigger` GitHub check failures in this pull-request.
Getting `webhook / test (3.12) (pull_request) ` to pass should be adequate for this pull-request.

**Comment by davidcavazos** [comment]
Okay, just `knowledge-base-trigger-sa` is 25 characters long. So what I'll do is that if `unique_names` is set to false which is what users will always do, we'll use the `knowledge-base-` prefix since it's nicer looking and more explicit. The `unique_names` are used for tests so that we can run multiple concurrent tests from different PRs, so those can use a `kb-` prefix to keep them shorter.

**Comment by NimJay** [comment]
> _"The unique_names are used for tests so that we can run multiple concurrent tests from different PRs"_

Ah, I see what you mean: the `webhook / test (3.12) (pull_request)` uses the same project for each pull-request.
For what it's worth, the `terraform-genai-knowledge-base-int-trigger` GitHub check does a `terraform apply` and `terraform destroy` test and creates a new project per pull-request (so we don't have to worry about parallel PRs).
Should we remove eventually remove `webhook / test (3.12)` when we get https://github.com/GoogleCloudPlatform/terraform-genai-knowledge-base/pull/88 work?
I'd love to hear your thoughts. (But of course, this discussion is out-of-scope for this PR.)

**Comment by davidcavazos** [comment]
I still like having the webhook tests since the other ones just test the deployment and the webhook tests check the logic. Plus they run a lot faster so it's easier to iterate over them.

**Review by NimJay — APPROVED** [review]
I'm approving this for correctness and so you can merge as soon as you've decided to merge.
But I'll leave it up to you to coordinate with Karl/Don on whether we should merge this _this_ week (before Console code freeze) or next week (after Console code freeze).

Updates to the Neos tutorial and Terraform inside GitHub aren't impacted by code freeze. So we can delay this change until next week.

**Comment by davidcavazos** [comment]
We're going to pause this for the code freeze, but I'll leave this open to have it ready to go.

**Pull request merged**
